### ISSUE TITLE
[🚀 feature] 글 즐겨찾기(Star) 기능을 구현한다.

### ISSUE THREAD

**Issue by shin-mallang** [Mallang-log/backend#84]
## ✅ 할 일
- [x] 글 즐겨찾기(Star) 기능은 `위시리스트`와 유사하다.
- [x] 로그인한 사용자만 글을 즐겨찾기할 수 있다.
- [x] 보호된 글에 대한 즐겨찾기 시, 비밀번호 필요
- [x] 보호, 비공개된 글에 대한 즐겨찾기 제거 시, 비밀번호가 필요하지 않다.
- [x] 특정 회원의 즐겨찾기 목록 조회가 가능해야 한다.
  - [x] 즐겨찾기한 글 목록은 모두에게 공개된다.
  - [x] 보호된 글은 보호되어 조회되어야 한다.
  - [x] 비공개 글은 조회되지 않는다.
  - [x] 보여지는 데이터는 즐겨찾기 ID와, 즐겨찾기일을 제외하면 일반 포스트 조회와 동일하다.

## TODO
- #22

**Comment by shin-mallang** [comment]
즐겨찾기 목록은 회원 프로필 페이지를 따로 만들어서 처리한다.
